name: Multi-Target CI/CD Pipeline

on:
  push:
    tags:
      - '*'  # Runs only when a tag is pushed (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract Git Tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push PHP 7.4-fpm Image
        run: |
          docker build --target sylius_php -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-php:7.4-fpm-${{ env.TAG_VERSION }} -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-php:latest ./images/php/7.4-fpm
          docker push ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-php:7.4-fpm-${{ env.TAG_VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-php:latest

      - name: Build and Push Nginx 1.24 Image
        run: |
          docker build --target sylius_nginx -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nginx:1.24-${{ env.TAG_VERSION }} -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nginx:latest ./images/nginx/1.24
          docker push ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nginx:1.24-${{ env.TAG_VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nginx:latest

      - name: Build and Push Nodejs 12 Image
        run: |
          docker build --target sylius_nodejs -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nodejs:12-${{ env.TAG_VERSION }} -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nodejs:latest ./images/nodejs/12
          docker push ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nodejs:12-${{ env.TAG_VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nodejs:latest