name: Multi-Target CI/CD Pipeline

on:
  push:
    tags:
      - '*'  # Runs only when a tag is pushed (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract Git Tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push PHP 7.4-fpm Image
        run: |
          docker buildx create --use
          docker buildx build --target sylius_php \
            -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-php:7.4-fpm-${{ env.TAG_VERSION }} \
            -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-php:latest \
            --push ./images/php/7.4-fpm

      - name: Build and Push Nginx 1.24 Image
        run: |
          docker buildx create --use
          docker buildx build --target sylius_nginx --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nginx:1.24-${{ env.TAG_VERSION }} \
            -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nginx:latest \
            --push ./images/nginx/1.24

      - name: Build and Push Nodejs 12 Image
        run: |
          docker buildx create --use
          docker buildx build --target sylius_nodejs --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nodejs:12-${{ env.TAG_VERSION }} \
            -t ${{ secrets.DOCKER_HUB_USERSPACE }}/sylius-nodejs:latest \
            --push ./images/nodejs/12